### PR TITLE
Added the ability to calculate projected DOS

### PR DESCRIPTION
**Pull request by elinscott**
pDOS calculation is now supported. The pDOS will be generated if...
- a wannierization or dft_bands task is being performed
- the pseudos being used have the required `PP_PSWFC` entries
- the degauss is suitably large compared to the density of the sampling of the k-path

We have also unified the plotting of bandstructures and DOSs. This is now performed with the function `workflow.plot_bandstructure(bs, dos, ...)` where if `dos` is not None it plots additionally the DOS alongside. Customisation of the plot can be performed via various keyword arguments. See `Workflow.plot_bandstructure(...)` for details.

Other minor changes:
- fixed error in the QE version tag `koopmans` was printing out
- fixed the printing of the "koopmans" header so it always appears before warnings, and appears when workflows are run from within python (which it previously did not)

### CODE REVIEW

**Review by degennar — CHANGES_REQUESTED** [review]
Thanks a lot Edward and Marija, just a few minor things:
- the pdos calculation goes well but is printed in the main directory (where the JSON file is) rather than in some subdir. Could you please make it run into a separate subdir?
- removing the file `koopmans/workflows/._wannierize.py.swp`
- is it possible to slightly increase the quality of the png picture produced at the end?
- it seems that some parameters in `plot` dictionary provided in input are overruled by the workflow (in particular `Emin`, `Emax`). I discovered that by running e.g. `test_03` while changing the values for those parameters.
- when running a `dft_bands` task for some reason after the `bands` calculation the workflow looks for the pseudopotential inside my personal default `PSEUDO_DIR` rather than in the directory relative to the library specified in input (in my case it was `pseudo_dojo_standard`). Here is the error:
```
  Running ./scf... done
  <QC> scf_energy -227.71692163294375
  Running ./bands... done
Traceback (most recent call last):
  File "/home/degennar/venvs/koopmans/bin/koopmans", line 11, in <module>
    load_entry_point('koopmans', 'console_scripts', 'koopmans')()
  File "/home/degennar/CODES/koopmans/koopmans/cli/main.py", line 51, in main
    workflow.run()
  File "/home/degennar/CODES/koopmans/koopmans/workflows/_workflow.py", line 264, in run
    self._run()
  File "/home/degennar/CODES/koopmans/koopmans/workflows/_dft.py", line 85, in _run
    n_filled = pseudopotentials.nelec_from_pseudos(self.atoms, self.pseudopotentials) // 2
  File "/home/degennar/CODES/koopmans/koopmans/pseudopotentials.py", line 131, in nelec_from_pseudos
    valences_dct = {key: valence_from_pseudo(value, pseudo_dir) for key, value in pseudopotentials.items()}
  File "/home/degennar/CODES/koopmans/koopmans/pseudopotentials.py", line 131, in <dictcomp>
    valences_dct = {key: valence_from_pseudo(value, pseudo_dir) for key, value in pseudopotentials.items()}
  File "/home/degennar/CODES/koopmans/koopmans/pseudopotentials.py", line 122, in valence_from_pseudo
    return int(float(read_pseudo_file(pseudo_dir / filename).find('PP_HEADER').get('z_valence')))
  File "/home/degennar/CODES/koopmans/koopmans/pseudopotentials.py", line 103, in read_pseudo_file
    upf = ET.parse(fd).getroot()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/degennar/pseudo/Si.upf'
```

**Comment by elinscott** [comment]
> * the pdos calculation goes well but is printed in the main directory (where the JSON file is) rather than in some subdir. Could you please make it run into a separate subdir?

Done; see [6eb5f53](https://github.com/epfl-theos/koopmans/pull/106/commits/6eb5f53ad2bc3831f3a4729dbd68aee56e3c1ab6)

**Comment by elinscott** [comment]
> * removing the file `koopmans/workflows/._wannierize.py.swp`

Done; see [50b9f57](https://github.com/epfl-theos/koopmans/pull/106/commits/50b9f5709f1d88fe10e5b0bddab11d465c15f628)

**Comment by elinscott** [comment]
> * is it possible to slightly increase the quality of the png picture produced at the end?

Done; see [50b9f57](https://github.com/epfl-theos/koopmans/pull/106/commits/50b9f5709f1d88fe10e5b0bddab11d465c15f628)

**Comment by elinscott** [comment]
> * when running a `dft_bands` task for some reason after the `bands` calculation the workflow looks for the pseudopotential inside my personal default `PSEUDO_DIR` rather than in the directory relative to the library specified in input (in my case it was `pseudo_dojo_standard`).

Done; see [6eb5f53](https://github.com/epfl-theos/koopmans/pull/106/commits/6eb5f53ad2bc3831f3a4729dbd68aee56e3c1ab6)

**Comment by elinscott** [comment]
> * it seems that some parameters in `plot` dictionary provided in input are overruled by the workflow (in particular `Emin`, `Emax`). I discovered that by running e.g. `test_03` while changing the values for those parameters.

Done; see [c99a311](https://github.com/epfl-theos/koopmans/pull/106/commits/c99a3114a46ca40ec8cebceaa161a30dc331e069). Note that this is a more ad-hoc fix that will be implemented more cleanly in #132

**Comment by elinscott** [comment]
Hopefully that's everything @degennar ? Thanks for being so thorough!

**Comment by degennar** [comment]
> > * the pdos calculation goes well but is printed in the main directory (where the JSON file is) rather than in some subdir. Could you please make it run into a separate subdir?
> 
> Done; see [6eb5f53](https://github.com/epfl-theos/koopmans/pull/106/commits/6eb5f53ad2bc3831f3a4729dbd68aee56e3c1ab6)

Great, now the `dft_bands` is doing fine. When I run a `wannierise` task or a koopmans calculation the pdos calculation still runs in a "main" dir though. In the first case it runs in the dir containing the JSON file, in the second case it runs in `postproc` (I used the same input of before, simply switching from dft_bands to wannierise and to singlepoint).

**Comment by degennar** [comment]
Took the freedom to update a warning message since I happened to see it ([1094132](https://github.com/epfl-theos/koopmans/pull/106/commits/109413248e9ad2f9a23536c9a4e83649b3607b0c)).

**Comment by degennar** [comment]
> > * it seems that some parameters in `plot` dictionary provided in input are overruled by the workflow (in particular `Emin`, `Emax`). I discovered that by running e.g. `test_03` while changing the values for those parameters.
> 
> Done; see [c99a311](https://github.com/epfl-theos/koopmans/pull/106/commits/c99a3114a46ca40ec8cebceaa161a30dc331e069). Note that this is a more ad-hoc fix that will be implemented more cleanly in #132

Sorry, in my head that PR was already in. All good then :)

**Comment by elinscott** [comment]
> > > * the pdos calculation goes well but is printed in the main directory (where the JSON file is) rather than in some subdir. Could you please make it run into a separate subdir?
> > 
> > 
> > Done; see [6eb5f53](https://github.com/epfl-theos/koopmans/pull/106/commits/6eb5f53ad2bc3831f3a4729dbd68aee56e3c1ab6)
> 
> Great, now the `dft_bands` is doing fine. When I run a `wannierise` task or a koopmans calculation the pdos calculation still runs in a "main" dir though. In the first case it runs in the dir containing the JSON file, in the second case it runs in `postproc` (I used the same input of before, simply switching from dft_bands to wannierise and to singlepoint).

Hopefully that should be sorted now ([554af0f](https://github.com/epfl-theos/koopmans/pull/106/commits/554af0f924b93c07bb1c016c641e6a3ec2331401))

**Review by degennar — APPROVED** [review]

**Pull request merged**
