### PR TITLE
Calculation of bands

### PR DESCRIPTION
**Pull request by degennar**
Bands are normally calculated by default when `periodic=true`, disregarding the value of `calculate_bands` in input.

Now, if `calculate_bands=false` the workflow does not include any band structure calculation (at any of the PW, Wannier90, or UI levels).

The parameters defined for DOS calculations (`degauss`, `nstep`, `Emin`, `Emax`), so far within the `ui` block, have been moved to a new block called `plot`.
`plot_params` is a new attribute of any workflow object, and it contains the information about these plot parameters. This is also inherited as a parameter by the `UnfoldAndInterpolateCalculator`.

### CODE REVIEW

**Comment by elinscott** [comment]
> Points to discuss:
> 
> * reactivate scf_kgrid (line 53 of `workflows/_unfold_and_interpolate.py`) and regenerate the benchmark
Done
> * problem when calling `ase.dft.DOS` from a workflow object
I can't remember what this related to but I think we discussed and it was fine?
> * do not understand when the UI bands are plotted since the plot is in `WannierizeWorkflow`
See all instances of `self.plot_bandstructure()`
> * how to pass `plot_params` to all the calculators
They do not need to be passed to the calculators, because the plotting is handled by the workflow object 
> * at the moment `get_energy_range` is an attribute belonging to `UnfoldAndInterpolateCalculator` only; this is also needed in `WannierizeWorkflow` to get `Emin`, `Emax` when they are not defined. Also we need to find a smarter way to define `Emin`, `Emax` for band structure plots since they are different from calculation to calculation (e.g. take global max and min, but this is not so straightforward).
This we should perhaps discuss in person, we have one of two choices: go with the default for ASE (I think it is -10 to +5) or alternatively plot the entire band strucutre (the current behaviour of `get_energy_range()`). Perhaps worthy of further in-person discussion 
> * regenerate the benchmark
Done!

**Review by elinscott — APPROVED** [review]
Looks good to me!

**Comment by degennar** [comment]
> > * problem when calling `ase.dft.DOS` from a workflow object
> 
> I can't remember what this related to but I think we discussed and it was fine?

Actually, after the quick discussion that we had few days ago this was not an issue anymore.

**Comment by degennar** [comment]
> > * at the moment `get_energy_range` is an attribute belonging to `UnfoldAndInterpolateCalculator` only; this is also needed in `WannierizeWorkflow` to get `Emin`, `Emax` when they are not defined. Also we need to find a smarter way to define `Emin`, `Emax` for band structure plots since they are different from calculation to calculation (e.g. take global max and min, but this is not so straightforward).
> 
> This we should perhaps discuss in person, we have one of two choices: go with the default for ASE (I think it is -10 to +5) or alternatively plot the entire band structure (the current behaviour of `get_energy_range()`). I'm inclined to just go along with ASE, and delete `get_energy_range()` entirely. @degennar what do you think?

I agree, let's keep ASE's default. In the end, it's up to the user to define the right values for those parameters. Also rerunning just that part of the workflow is pretty fast so it would not be a big deal.

**Comment by elinscott** [comment]
> I agree, let's keep ASE's default. In the end, it's up to the user to define the right values for those parameters. Also rerunning just that part of the workflow is pretty fast so it would not be a big deal. @elinscott this is the current default right?

Indeed, we'll now default to ASE's -10 to +5 eV, and if a user didn't like their plot they could just change Emin and Emax and rerun not from scratch.

**Pull request merged**
